@base_url = http://localhost:3000

###
POST {{base_url}}/cats
Content-Type: application/json

{
  "id": 1,
  "name": "mike",
  "age": 3,
  "breed": "k2o"
}

###
GET {{base_url}}/cats

###
@id = 1
GET {{base_url}}/cats/{{id}}
